base_url = "https://blog.tinikov.com"
title = "RE:137"
description = "时间是唯一致死的毒药。"
default_language = "zh-cn"
compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml"]
author = "季尼柯夫"
taxonomies = [{ name = "categories" }]

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

[extra]
seo = true
ogimage = "nagara_sq.jpg"
google_search_console = "iXrh4pewdBSA1GlOHtTe_8IggFXgxgZujXKPikaS36M"

indiewebring = true
mastodon = "https://o3o.ca/@tinikov"
github = "tinikov"

establishdate = "2018"

license = true

zola_theme = true

header_links = [
    { url = "$BASE_URL", name = "主页" },
    { url = "$BASE_URL/categories", name = "分类" },
    { url = "$BASE_URL/about", name = "关于" },
    { url = "$BASE_URL/link", name = "连结" },
    { url = "$BASE_URL/space-like", name = "类空区" },
    { url = "$BASE_URL/withbb", name = "猪言猪语" },
    { url = "$BASE_URL/rss.xml", name = "RSS" },
]
