base_url = "https://re137.vercel.app"
title = "Re137"
description = "A Chinese friendly zola theme. Inspired by lightspeed."
default_language = "zh-cn"
compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml"]
author = "tinikov"

# If used as theme, please uncomment this option
# theme = "Re137"

# To enable categories page
taxonomies = [{ name = "categories" }]

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

[extra]
# Image shown when you share this website to others
# ogimage = " "

# SEO settings
# seo = true
# google_search_console = " "

# Show jump buttons for Indiewebring
# indiewebring = true

# For authentication in mastodon
# mastodon = "https://o3o.ca/@tinikov"

# Only user name is needed
# github = "tinikov"

# Show establish date in the footer
establishdate = "2024"

# CC BY-NC 4.0 (https://creativecommons.org/licenses/by-nc/4.0/)
license = true

# Show "🫧 Zola theme re137" in the footer
show_zola_theme = true

# You can add your own items to list in the site navigator
re137_menu_links = [
    { url = "$BASE_URL", name = "主页" },
    { url = "$BASE_URL/categories", name = "分类" }, # If enabled "taxonomies"
    { url = "$BASE_URL/about", name = "关于" },
    { url = "$BASE_URL/rss.xml", name = "RSS" },
]
